name: GitHub Actions Build and Deploy Project
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install and Publish
      run: yarn install && yarn run publish
      env:
        GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
